"""added match details fields to Match model

Revision ID: 0c96896a0283
Revises: 2c7f91b8675e
Create Date: 2020-11-21 16:24:13.070827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c96896a0283'
down_revision = '2c7f91b8675e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('match', sa.Column('venue', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_match_date'), 'match', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_date'), table_name='match')
    op.drop_column('match', 'venue')
    op.drop_column('match', 'date')
    # ### end Alembic commands ###
